"""Generate the small Lua catalog used by the real signpost menu (no runtime JSON dependency)."""
import json
from pathlib import Path


def render(manifest, overlay):
    # IDs/names in this selected source are ASCII; JSON escaping is Lua-compatible here.
    def quote(value):
        return json.dumps(value, ensure_ascii=True)
    lines = ["-- Generated by Scripts/digimon_terminal_catalog.py; do not edit by hand.",
             "return {", "  species = {"]
    for entry in sorted(manifest["digimon"], key=lambda x: x["id"]):
        lines.append(f"    {{ id = {quote(entry['id'])}, name = {quote(entry['name'])} }},")
    lines += ["  },", "  scan = {"]
    for key in ("points_per_defeat", "unlock_threshold", "points_per_species_per_floor",
                "overflow_bits_per_point", "restoration_level", "restoration_levels_per_threshold", "restoration_maximum_level"):
        value = overlay["scan"][key]
        if type(value) is not int or value < 0:
            raise ValueError(f"Invalid scan setting: {key}")
        lines.append(f"    {key} = {value},")
    return "\n".join(lines + ["  }", "}", ""])


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    data = root / "DataAsset" / "Digimon"
    output = root / "DumpAsset" / "Data" / "Script" / "origin" / "digimon" / "catalog.lua"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(json.loads((data / "phase1_manifest.json").read_text()),
                             json.loads((data / "phase1_overlay.json").read_text())),
                      encoding="utf-8", newline="\n")
    print(f"Wrote {output}")
