#!/usr/bin/env python3
"""Validate the family-item design and render its matrix to docs/DIGIMON_FAMILY_ITEMS.md.

The items themselves are generated by ``DataGenerator -digimon-items``; this script checks
the design against the kept families and the PMDO effect catalog before that step, and
writes the review document afterwards.
"""
from __future__ import annotations

import collections
import json
import re
from pathlib import Path

from digimon_runtime_assets import family_assignments, read

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / 'DataAsset/Digimon/family_items.json'
DOC = ROOT / 'docs/DIGIMON_FAMILY_ITEMS.md'
TIER_LABEL = {1: '★', 2: '★★', 3: '★★★'}
TIER_SOURCE = {1: 'treasure box (rarity 1)', 2: 'deep treasure box (rarity 2)', 3: 'swap shop'}
ELEMENT_NAME = {'normal': 'Neutral', 'fire': 'Fire', 'water': 'Water', 'grass': 'Plant', 'electric': 'Electric',
                'ground': 'Earth', 'flying': 'Wind', 'fairy': 'Light', 'dark': 'Dark'}
STAT_NAME = {'HP': 'HP', 'Attack': 'Attack', 'Defense': 'Defense', 'MAtk': 'Special Attack', 'MDef': 'Special Defense', 'Speed': 'Speed'}
# A single effect-and-parameter combination may serve at most this many families.
MAX_SHARED = 2


def slug(family: str) -> str:
    return re.sub(r'[^a-z0-9]+', '_', family.lower()).strip('_')


def item_id(family: str, index: int) -> str:
    return f'digixcl_{slug(family)}_{index:02d}'


def effect_catalog() -> dict[str, str]:
    """Effect name -> player-facing template, from the PMDO string table."""
    rows = (ROOT / 'DataAsset/String/ExclusiveItemEffect.out.txt').read_text(encoding='utf-8').splitlines()
    out = {}
    for line in rows[1:]:
        cols = line.split('\t')
        out[cols[0].split('.')[-1]] = cols[2] if len(cols) > 2 else ''
    return out


def display(value: str, kind: str) -> str:
    if kind == 'element':
        return ELEMENT_NAME.get(value, value.title())
    if kind == 'stat':
        return STAT_NAME.get(value, value)
    if kind == 'status':
        path = ROOT / 'DumpAsset/Data/Status' / f'{value}.json'
        return read(path)['Object']['Name']['DefaultText'] if path.exists() else value
    if kind == 'map_status':
        path = ROOT / 'DumpAsset/Data/MapStatus' / f'{value}.json'
        return read(path)['Object']['Name']['DefaultText'] if path.exists() else value
    return value


def describe(item: dict, templates: dict[str, str]) -> str:
    """Fill the PMDO template with this item's parameters, in sheet column order."""
    args = []
    for key, kind in (('element', 'element'), ('status', 'status'), ('stat', 'stat'), ('target_element', 'element'),
                      ('category', 'category'), ('quantity', 'quantity'), ('map_status', 'map_status')):
        if key in item:
            args.append(display(str(item[key]), kind))
    text = templates.get(item['effect'], '')
    # MapStatusOnCategoryUse reads category first; every other effect follows column order.
    try:
        text = text.format(*args)
    except (IndexError, KeyError):
        pass
    for src, dst in (('Pokémon', 'Digimon'), ('Pokemon', 'Digimon'), ('Fairy-type', 'Light-type'), ('Grass-type', 'Plant-type'),
                     ('Ground-type', 'Earth-type'), ('Flying-type', 'Wind-type'), ('Normal-type', 'Neutral-type')):
        text = text.replace(src, dst)
    return text.replace('When kept in the bag, ', '').strip()


def validate(design: dict, families: dict[str, list[str]], effects: set[str]) -> list[str]:
    problems = []
    seen_families, ids, names = set(), set(), set()
    combos = collections.defaultdict(set)
    for row in design['families']:
        family = row['family']
        if family not in families:
            problems.append(f'unknown family {family}')
            continue
        if family in seen_families:
            problems.append(f'family listed twice: {family}')
        seen_families.add(family)
        tiers = collections.Counter()
        for index, item in enumerate(row['items'], 1):
            iid = item_id(family, index)
            if iid in ids:
                problems.append(f'duplicate id {iid}')
            ids.add(iid)
            if item['name'] in names:
                problems.append(f'duplicate name {item["name"]}')
            names.add(item['name'])
            if item['tier'] not in (1, 2, 3):
                problems.append(f'{iid}: bad tier {item["tier"]}')
            tiers[item['tier']] += 1
            if item['effect'] not in effects:
                problems.append(f'{iid}: unknown effect {item["effect"]}')
            key = (item['effect'],) + tuple(sorted((k, str(v)) for k, v in item.items() if k not in ('tier', 'name', 'effect')))
            combos[key].add(family)
        for tier in (1, 2, 3):
            if tiers[tier] == 0:
                problems.append(f'{family}: no {TIER_LABEL[tier]} item')
        size = len(families[family])
        minimum = 5 if size >= 15 else 4 if size >= 10 else 3
        if len(row['items']) < minimum:
            problems.append(f'{family}: {len(row["items"])} items for {size} members, expected at least {minimum}')
    for family in families:
        if family not in seen_families:
            problems.append(f'family without items: {family}')
    for key, owners in combos.items():
        if len(owners) > MAX_SHARED:
            problems.append(f'effect {key[0]} with the same parameters is shared by {sorted(owners)}')
    return problems


def render(design: dict, families: dict[str, list[str]], names: dict[str, str], templates: dict[str, str]) -> str:
    lines = ['# Digimon family items', '',
             'Design matrix for the family-exclusive items. Source of truth: `DataAsset/Digimon/family_items.json`;',
             'families come from `docs/DIGIMON_FAMILY_TYPES.md`. Items are generated with',
             '`DataGenerator -digimon-items` and reuse PMDO exclusive-item effects; no new battle code.', '',
             '## How it works', '',
             '- **Eligibility.** Each item carries the family\'s member species in PMDO\'s `FamilyState`, filled from the',
             '  installed Digimon forms. Because the check is against the holder\'s current species, digivolving into or',
             '  out of a family updates eligibility with no extra code. A Digimon in several families can use any of them;',
             '  one held item at a time means effects never stack.',
             '- **Drops.** ★ items are rarity 1 and ★★ items rarity 2. Treasure boxes roll from the species-to-rarity map',
             '  using the species present on that floor, so a box near Reptiles holds Reptile treasures. Light boxes use',
             '  rarity 1, deep boxes rarity 2. ★★★ items are rarity 3 and never drop.',
             '- **Exchange.** ★★★ items come from the Base Camp swap shop for the family\'s first ★ and first ★★ item.',
             '  Recipes are generated into `origin/digimon/family_trades.lua`.',
             '- **Names.** Player-facing text says Digimon and uses Digimon element names (Light for fairy, Plant for',
             '  grass, Earth for ground, Wind for flying, Neutral for normal).', '',
             '## Rebuild', '', '```text', 'python Scripts/digimon_family_items.py', 'dotnet build PMDOData.sln --no-restore',
             'cd DataGenerator/bin/Debug/net8.0', 'dotnet DataGenerator.dll -asset ../../../../DumpAsset/ -digimon-items ../../../../DataAsset/Digimon/family_items.json',
             'dotnet DataGenerator.dll -asset ../../../../DumpAsset/ -index Item', 'dotnet DataGenerator.dll -asset ../../../../DumpAsset/ -digimon-check', '```', '',
             'The first command validates the design and rewrites this file. The item index step also rebuilds the',
             'species-to-rarity map in `Data/Misc/Rarity.json` that treasure boxes read.', '',
             '## Matrix', '']
    total = 0
    for row in design['families']:
        family = row['family']
        members = families[family]
        sample = ', '.join(names[m] for m in members[:5]) + (' ...' if len(members) > 5 else '')
        lines += [f'### {family} ({len(members)} members)', '', f'*{row["theme"]}* Representative: {sample}.', '',
                  '| Tier | Item | Effect | PMDO effect | Source |', '| --- | --- | --- | --- | --- |']
        for index, item in enumerate(row['items'], 1):
            total += 1
            lines.append(f'| {TIER_LABEL[item["tier"]]} | {item["name"]} | {describe(item, templates)} | `{item["effect"]}` | {TIER_SOURCE[item["tier"]]} |')
        tops = [item['name'] for item in row['items'] if item['tier'] == 3]
        first1 = next(item['name'] for item in row['items'] if item['tier'] == 1)
        first2 = next(item['name'] for item in row['items'] if item['tier'] == 2)
        lines += ['', f'Exchange: {", ".join(tops)} for {first1} + {first2}.', '']
    lines.insert(lines.index('## Matrix'), f'{len(design["families"])} families, {total} items.\n')
    return '\n'.join(lines) + '\n'


def main() -> None:
    design = json.loads(DESIGN.read_text(encoding='utf-8'))
    rows = read(ROOT / 'DataAsset/Digimon/digimon_family_types.json')['family_types']
    assignments, removed, _ = family_assignments(rows)
    families = collections.defaultdict(list)
    for species_id, types in sorted(assignments.items()):
        for t in types:
            if t not in removed:
                families[t].append(species_id)
    names = {r['id']: r['name'] for r in rows}
    source = (ROOT / 'DataGenerator/Data/AutoItemInfo.cs').read_text(encoding='utf-8')
    enum = source[source.index('public enum ExclusiveItemEffect'):]
    enum = enum[:enum.index('}')]
    effects = set(re.findall(r'^\s*([A-Za-z]+),', enum, re.M))
    problems = validate(design, families, effects)
    if problems:
        raise SystemExit('Family item design problems:\n  ' + '\n  '.join(problems))
    DOC.write_text(render(design, families, names, effect_catalog()), encoding='utf-8')
    total = sum(len(row['items']) for row in design['families'])
    print(f'Family item design valid: {len(design["families"])}/{len(families)} families, {total} items. Wrote {DOC.relative_to(ROOT)}.')


if __name__ == '__main__':
    main()
